# kvx_file_to_esdb.toml — file source, Elasticsearch sink.
# The benchmark config. The one that makes graphs go up.
# NOAA weather data into Elasticsearch because weather is a solved problem
# and yet somehow still unpredictable. Like this codebase. 🌩️
# 🦆

[runtime]
queue_capacity = 32
sink_parallelism = 8

[source_config.File]
file_name = "benchmark/data/geonames.json"

[source_config.File.common_config]
max_batch_size_bytes = 33554432 # 128 * 1024 is a single read chunk * 256 read Kibibyte
max_batch_size_docs = 1000000

[sink_config.Elasticsearch]
url = "http://localhost:9200"
index = "test-123"
max_request_size_bytes = 4194304 # 128 * 1024 is a single read chuck * 64 chunks
